config/routes.rb
Blogger::Application.routes.draw do
  root :to => 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login' => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  attr_accessible :title, :body, :tag_list, :image

  def tag_list
  	tags.join(", ")
  end

  def tag_list=(tags_string)
  	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  	new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
  	self.tags = new_or_found_tags
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :require_login, except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@single_article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @single_article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
  		@article.save
  		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update_attributes(params[:article])

		flash.notice = "Article '#{@article.title}' Updated!"

		redirect_to article_path(@article)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_area :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br />
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
    <div><%= link_to link_to "<< Back to Articles List", articles_path %></div>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
	<% @articles.each do |article| %>
	<li>
		<%= link_to article.title, article_path(article) %>
	</li>
	<% end %>
	<% if logged_in? %>
		<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
	<% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @single_article.title %></h1>

<p>
	Tags:
	<% @single_article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
<p>
	<% if @single_article.image.exists? %>
		<%= image_tag @single_article.image.url %>
	<% end %>	
	</p>
<p>
	<%= @single_article.body %>
</p>

<br>
<br>
<% if logged_in? %>
	<%= link_to "edit", edit_article_path(@single_article) %>
	<br>
	<%= link_to "delete", article_path(@single_article), method: :delete, confirm: "Really delete the article?"
	 %>
<% end %>
 <br>
<br>
<h3>Comments (<%= @single_article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @single_article.comments %>
<%= render partial: 'comments/form' %>
<br>
<br>
<div><%= link_to "<< Back to Articles List", articles_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="flash"><%= flash.notice %></p>

	<div id="container">
	 	<div id="content">
	 		<%= yield %>
			<hr>
			<h6>
				<% if logged_in? %>
					<%= "Logged in as #{current_user.username}" %>
					<%= link_to "(logout)", logout_path %>					
				<% else %>
					<%= link_to "(login)", login_path %>
				<% end %>
			</h6>	
		</div>
	</div>
</body>
</html>